service: aws-apirest-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatement:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: index.handler
    events:
      - httpApi:
          path: /user
          method: post
  getUsers:
    handler: index.handler
    events:
      - httpApi:
          path: /users
          method: get
  getUserById:
    handler: index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get
  deleteUserById:
    handler: index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: delete
  putUserById:
    handler: index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: put
  createAnime:
    handler: index.handler
    events:
      - httpApi:
          path: /anime
          method: post
  getAnimes:
    handler: index.handler
    events:
      - httpApi:
          path: /animes
          method: get
  getAnimesByUser:
    handler: index.handler
    events:
      - httpApi:
          path: /users/{id}/animes
          method: get

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    AnimeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AnimeTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
plugins:
  - serverless-offline